version : "3.9"

services: 
    talent-dev:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "3015:3001"
        volumes:
            - .:/usr/src/app
